### ISSUE TITLE
Installation Failed! ERROR: Service 'react-storefront' failed to build : Build failed

### ISSUE THREAD

**Issue by SohelKabir** [saleor/saleor-platform#154] opened 2022-06-14 18:20 UTC
### What I'm trying to achieve
…

### Steps to reproduce the problem

1. Follow these steps for install https://docs.saleor.io/docs/3.x/developer/installation with docker
2. run `docker-compose build`

### What I expected to happen
…

executor failed running [/bin/sh -c pnpm install]: exit code: 1
ERROR: Service 'react-storefront' failed to build : Build failed

### Screenshots and logs

[](url)

**System information**

Saleor version:
- [ ] dev (current main)

Operating system:
- [ ] Windows

**Comment by Crepu** [comment] 2022-07-02 17:55
Hi everyone

I was getting the same problem and the @SohelKabir solution worked out with an exception. 

I'm working on a Linux (Ubuntu 20) machine and when I tried to install yarn globally, docker give me EEXIST code error. It seems I've already got yarn installed previously, so the build failed. 

By removing the global flag work like a charm.

**Comment by Ian2012** [comment] 2022-07-11 04:10
Hi everyone, the right solution is this one: https://github.com/saleor/saleor/issues/9764

I spent three days testing every solution and this is the right

**Comment by RashiqAzhan** [comment] 2022-07-22 15:40
The issue is still here. Is the solution here or https://github.com/saleor/saleor/issues/9764 the accepted solution? I can help with a PR if any of this is a recommended solution.

**Comment by Ian2012** [comment] 2022-07-22 15:53
That's the right solution. Please make a PR

**Comment by lkostrowski** [comment] 2022-07-28 07:49
Here is an issue that will fix it in the future
https://github.com/saleor/react-storefront/issues/275

This PR updates Saleor packages, so it should also solve the problem
https://github.com/saleor/saleor-platform/pull/158

**Comment by lkostrowski** [comment] 2022-07-28 12:48
https://github.com/saleor/saleor-platform/pull/158 was merged, which means react-storefront was updated to the newest version. 
It applies a fix for pnpm issue.

The issue should be solved, so I close this one.

**Closed by lkostrowski** 2022-07-28 12:48 UTC
Labels: bug
