### ISSUE TITLE
keep getting node_modules missing during compose up

### ISSUE THREAD

**Issue by hakampahimi** [saleor/saleor-platform#32] opened 2020-05-08 04:10 UTC
getting this error when starting storefront

storefront_1  | 
storefront_1  | > saleor-site@2.10.0-rc.2 start /app
storefront_1  | > cross-env NODE_ENV=develop webpack-dev-server --history-api-fallback --watch --port 3000 --mode development --hotOnly "--host" "0.0.0.0"
storefront_1  | 
storefront_1  | sh: 1: cross-env: not found
storefront_1  | npm ERR! code ELIFECYCLE
storefront_1  | npm ERR! syscall spawn
storefront_1  | npm ERR! file sh
storefront_1  | npm ERR! errno ENOENT
storefront_1  | npm ERR! saleor-site@2.10.0-rc.2 start: `cross-env NODE_ENV=develop webpack-dev-server --history-api-fallback --watch --port 3000 --mode development --hotOnly "--host" "0.0.0.0"`
storefront_1  | npm ERR! spawn ENOENT
storefront_1  | npm ERR! 
storefront_1  | npm ERR! Failed at the saleor-site@2.10.0-rc.2 start script.
storefront_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
storefront_1  | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
storefront_1  |

**Comment by maarcingebala** [comment] 2020-05-19 09:12
Hey, please try to rebuild your containers, it should help when they're failing to build for some reason: https://github.com/mirumee/saleor-platform#how-to-solve-issues-with-lack-of-available-space-or-build-errors-after-update

**Comment by arddluma** [comment] 2020-05-24 01:26
Looks like the issue is with RAM size,
I change the EC2 instance type from t2.micro to t2.medium and it worked !

**Comment by ocelot2123** [comment] 2021-04-14 08:32
if anybody faces this on Linux (which shouldn't be a RAM issue as Docker should have access to all physical RAM unless you limited it manually previous or actually have limited physical RAM)
I managed to solve it by downgrading my Docker version to 19.03.9

**Comment by xg1990** [comment] 2021-05-22 23:28
same problem happened to me. And I should have enough memory

<img width="684" alt="image" src="https://user-images.githubusercontent.com/1443518/119243360-3354e180-bba9-11eb-905c-db0fa129f106.png">

**Comment by lkostrowski** [comment] 2022-12-12 08:58
Hi

Images in saleor-platform have changed a lot. Closing for now, please open new issue in case of any new problems

**Closed by lkostrowski** 2022-12-12 08:58 UTC
Labels: support
